### ISSUE TITLE
Block hash değeri neden 0 ?

### ISSUE THREAD

**Issue by ghost** [onuar/dokuztas#1]
Aşağıdada gördüğüm kadarıyla başlangıç bloğunun hash değeri 0 olarak veriliyor.
https://github.com/onuar/dokuztas/blob/80f4fa0747b0062c3ba7e46d24b716c8cbb5dea7/dokuztas/blockchain.py#L17

Fakat kriptoparalarda başlangıç bloğuda bir hash değerine sahip.
- [Monero başlangıç bloğu](https://moneroblocks.info/search/1)
- [Litecoin başlangıç bloğu](https://live.blockcypher.com/ltc/block/12a765e31ffd4059bada1e25190f6e98c99d9714d334efa41a195a7e7e04bfe2/)

Başlangıç bloğununda bir hash değerine sahip olması daha doğru olmaz mı?

**Comment by onuar** [comment]
Kesinlikle. Block header hash'leri 0 olmamalı.

**Comment by onuar** [comment]
Artık genesis block'u da mine ediliyor. Bu sayede blockhash'i hesaplanılarak yazılıyor. 

Ayrıca test senaryosu da eklendi.
