### ISSUE TITLE
Dağıtık ağ sistemi

### ISSUE THREAD

**Issue by kai-hiwatari** [onuar/dokuztas#6]
Sabit bir sunucu değilde dağıtık bir ağ nasıl kurulur ?

**Comment by onuar** [comment]
Şunlar işinizi görecektir.

https://ethereum.stackexchange.com/questions/7743/what-are-the-peer-discovery-mechanisms-involved-in-ethereum
https://en.bitcoin.it/wiki/Satoshi_Client_Node_Discovery
https://bitcoin.stackexchange.com/questions/3536/how-do-bitcoin-clients-find-each-other

**Comment by kai-hiwatari** [comment]
teşekkürler
